#!/bin/sh
# /etc/init.d/test

### BEGIN INIT INFO
# Provides:          notificaciones
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: notificaciones
# Description:       notificaciones
### END INIT INFO


 case "$1" in
  start)
    sudo python /home/pi/desarrollo/raspberry-pi/noticias/notificaciones.py &
    ;;
  stop)
    killall python
    ;;
  *)
    exit 1
    ;;

esac
exit 0